export default {
  enableCollapseSearch: false,
  route: "/", // 標記是哪個頁面include ejs
  filter: "精選", // 預設gallery要顯示的標籤
  interests: [
    {
      id: 0,
      titleZH: "木工",
      titleEN: "Woodworking",
    },
    {
      id: 1,
      titleZH: "文具",
      titleEN: "Stationery",
    },
    {
      id: 2,
      titleZH: "紙藝",
      titleEN: "Paper Crafts",
    },
    {
      id: 3,
      titleZH: "繪畫和插畫",
      titleEN: "Painting and Illustration",
    },
    {
      id: 4,
      titleZH: "雕刻",
      titleEN: "Sculpture",
    },
    {
      id: 5,
      titleZH: "皮革製品",
      titleEN: "Leather Goods",
    },
    {
      id: 6,
      titleZH: "環保再生製品",
      titleEN: "Eco-friendly Upcycled Products",
    },
    {
      id: 7,
      titleZH: "軟玩具和娃娃",
      titleEN: "Soft Toys and Dolls",
    },
    {
      id: 8,
      titleZH: "拼貼和雕貼",
      titleEN: "Collage and Decoupage",
    },
    {
      id: 9,
      titleZH: "影視手工藝",
      titleEN: "Film and TV Crafts",
    },
    {
      id: 10,
      titleZH: "DIY工具和工藝材料",
      titleEN: "DIY Tools and Craft Materials",
    },
  ],
  hotNow: [
    {
      id: 0,
      titleZH: "設計家具",
      titleEN: "Design Furniture",
    },
    {
      id: 1,
      titleZH: "婚禮小物",
      titleEN: "Wedding Accessories",
    },
    {
      id: 2,
      titleZH: "旅行用品",
      titleEN: "Travel Goods",
    },
    {
      id: 3,
      titleZH: "手工花藝",
      titleEN: "Handmade Floral",
    },
    {
      id: 4,
      titleZH: "環保愛地球",
      titleEN: "Environmental Friendly",
    },
    {
      id: 5,
      titleZH: "香氛蠟燭",
      titleEN: "Scented Candle",
    },
  ],
  materials: [
    "木材",
    "金屬",
    "玻璃",
    "陶瓷",
    "布料、紡織品",
    "皮革",
    "紙張、紙板",
    "塑料",
    "石材",
    "珠寶材料",
    "粘土",
    "植物材料",
    "電子元件",
    "食品材料",
    "水彩、油畫顏料",
    "蠟燭材料",
    "香薰材料",
    "環保再生材料",
    "石膏、混凝土",
    "軟性材質",
    "酸性材質",
    "金箔、銀箔",
    "複合材料",
    "其他",
  ],
  category: [
    "木工",
    "飾品",
    "文具",
    "織品",
    "陶瓷和陶器",
    "粘土創作",
    "珠寶",
    "紙藝",
    "玻璃工藝",
    "古董和復古裝飾",
    "繪畫和插畫",
    "雕刻",
    "皮革製品",
    "美食工藝",
    "蠟燭和香薰",
    "音樂和樂器",
    "環保再生製品",
    "植物和園藝",
    "軟玩具和娃娃",
    "拼貼和雕貼",
    "電子手工藝",
    "空間設計和裝飾",
    "影視手工藝",
    "創意裝置藝術",
    "DIY工具和工藝材料",
  ],
  crafts: [
    {
      id: 0,
      title: "香氛蠟燭",
      description:
        "散發著迷人香氛的蠟燭，讓您瞬間放鬆並營造溫馨氛圍。完美選擇，無論是為了為家裡增添溫馨氛圍，或送給親朋好友，帶來特別的禮物體驗。",
      tags: ["聖誕節", "可愛", "新人作品"],
      imgURLs: [
        "https://images.unsplash.com/photo-1612293905607-b003de9e54fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
        "https://images.unsplash.com/photo-1610283795609-edb9f19436a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1972&q=80",
        "https://images.unsplash.com/photo-1570823635306-250abb06d4b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        "https://images.unsplash.com/photo-1613068431228-8cb6a1e92573?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
        "https://images.unsplash.com/photo-1604172083143-081d302edb4d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEyfHx8ZW58MHx8fHx8&auto=format&fit=crop&w=500&q=60",
      ],
      shopLinks: [""],
      author: "飛行兔子",
      like: 5,
      created: "2023-09-16",
    },
    {
      id: 1,
      title: "針織窗簾",
      description: "精心製作的針織窗簾，為您的家居增添溫馨氛圍。",
      tags: ["精選", "窗簾", "針織"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select1-f60158f9.png"],
      shopLinks: [""],
      author: "",
      like: 8,
      created: "2023-09-17",
    },
    {
      id: 2,
      title: "乾燥花花盆",
      description: "特製的花盆，搭配精選乾燥花卉，為您的室內空間增色不少。",
      tags: ["精選", "花盆", "乾燥花", "熱門"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select2-d860d3f7.png"],
      shopLinks: [""],
      author: "",
      like: 3,
      created: "2023-09-18",
    },
    {
      id: 3,
      title: "愛心裝飾",
      description: "手工打造的愛心裝飾，帶來愛和溫暖的氛圍，適合用於家居裝飾或送禮。",
      tags: ["精選", "愛心", "裝飾", "熱門", "聖誕節"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select3-8dd5cb59.png"],
      shopLinks: [""],
      author: "",
      like: 12,
      created: "2023-09-19",
    },
    {
      id: 4,
      title: "陶杯",
      description: "手工製作的陶瓷杯，質感優良，為您的茶時光增色不少。",
      tags: ["精選", "陶杯", "陶瓷"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select6-b3af49bd.png"],
      shopLinks: [""],
      author: "",
      like: 15,
      created: "2023-09-22",
    },
    {
      id: 5,
      title: "乾燥花",
      description: "精心挑選的乾燥花束，保留了自然美，為您的生活增添了一抹自然的色彩。",
      tags: ["精選", "乾燥花", "花束", "新人作品"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select4-7bfd310d.png"],
      shopLinks: [""],
      author: "",
      like: 2,
      created: "2023-09-20",
    },
    {
      id: 6,
      title: "毛線袋子",
      description: "經過精湛的毛線工藝製作而成，輕巧實用，是您日常生活的好幫手。",
      tags: ["精選", "毛線", "袋子"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select5-5d3b52a9.png"],
      shopLinks: [""],
      author: "",
      like: 9,
      created: "2023-09-21",
    },
    {
      id: 7,
      title: "手工肥皂架",
      description: "精心製作的手工肥皂架，美觀實用，讓肥皂保持乾燥，延長使用壽命。",
      tags: ["精選", "肥皂架", "手工", "熱門"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select7-5797d2c1.png"],
      shopLinks: [""],
      author: "",
      like: 6,
      created: "2023-09-23",
    },
    {
      id: 8,
      title: "手工肥皂",
      description: "純手工製作，天然成分，呵護您的肌膚，讓您感受自然的清新。",
      tags: ["精選", "手工肥皂", "天然"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select9-06038d2a.png"],
      shopLinks: [""],
      author: "",
      like: 7,
      created: "2023-09-25",
    },
    {
      id: 9,
      title: "檸檬陶盤",
      description: "以檸檬為靈感，手工打造的陶瓷盤子，為您的餐桌增添一份清新。",
      tags: ["精選", "陶盤", "檸檬", "新人作品"],
      imgURLs: ["https://raw.githubusercontent.com/Len5464/hiCraft/gh-pages/assets/craft-select8-5b56d0df.png"],
      shopLinks: [""],
      author: "",
      like: 10,
      created: "2023-09-24",
    },
    {
      id: 10,
      title: "復古伏特床頭燈",
      description: "經典的復古風格，精心製作的床頭燈，為您的臥室增添懷舊氛圍。",
      tags: ["復古", "床頭燈", "熱門"],
      imgURLs: [
        "https://images.unsplash.com/photo-1691984108700-174c64cc6634?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 11,
      created: "2023-10-07",
    },
    {
      id: 11,
      title: "籐編側背包",
      description: "精心編織的側背包，以天然的籐材料製成，簡約時尚，是您的日常時尚必備品。",
      tags: ["籐編", "側背包", "新人作品"],
      imgURLs: [
        "https://images.unsplash.com/photo-1527383214149-cb7be04ae387?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 4,
      created: "2023-09-26",
    },
    {
      id: 12,
      title: "編織花盆吊籃",
      description: "手工編織的花盆吊籃，美觀實用，讓您的植物成為裝飾的亮點。",
      tags: ["編織", "花盆吊籃", "新人作品"],
      imgURLs: [
        "https://images.unsplash.com/photo-1633594308237-3dcfa56b4e69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2080&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 6,
      created: "2023-09-27",
    },
    {
      id: 13,
      title: "手工果醬",
      description: "純手工製作的果醬，以新鮮水果為原料，保留了自然風味，為您的早餐增色不少。",
      tags: ["果醬", "手工", "新人作品"],
      imgURLs: [
        "https://images.unsplash.com/photo-1493236272120-200db0da1927?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 9,
      created: "2023-09-28",
    },
    {
      id: 14,
      title: "彩釉花瓶",
      description: "精美的彩釉花瓶，經過高溫燒製，色彩豐富，為您的花卉增色不少。",
      tags: ["彩釉", "花瓶", "熱門"],
      imgURLs: [
        "https://images.unsplash.com/photo-1529136595463-682e2527c25d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1256&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 8,
      created: "2023-09-30",
    },
    {
      id: 15,
      title: "廢五金西洋棋",
      description: "巧妙地利用廢五金打造的西洋棋，結合藝術與遊戲的完美組合。",
      tags: ["廢五金", "西洋棋", "熱門"],
      imgURLs: [
        "https://images.unsplash.com/photo-1577643893548-4d601ef89513?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 10,
      created: "2023-10-02",
    },
    {
      id: 16,
      title: "七彩琉璃吊燈",
      description: "精緻的琉璃吊燈，以七彩色彩為特色，營造出夢幻般的照明效果。",
      tags: ["琉璃", "吊燈", "熱門"],
      imgURLs: [
        "https://images.unsplash.com/photo-1582805043942-a96643809eeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 7,
      created: "2023-10-01",
    },
    {
      id: 17,
      title: "木造小恐龍",
      description: "精緻的木造小恐龍模型，以天然木材製成，是收藏和裝飾的理想選擇。",
      tags: ["木造", "恐龍", "熱門"],
      imgURLs: [
        "https://images.unsplash.com/photo-1563901935883-cb61f5d49be4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 3,
      created: "2023-09-29",
    },
    {
      id: 18,
      title: "復活節彩蛋",
      description: "手工製作的彩繪彩蛋，充滿節日氛圍，是復活節裝飾的理想選擇。",
      tags: ["復活節", "聖誕節", "彩蛋", "新人作品"],
      imgURLs: [
        "https://images.unsplash.com/photo-1516007415177-af5e62c69ebe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 6,
      created: "2023-10-03",
    },
    {
      id: 19,
      title: "毛線泰迪熊",
      description: "精緻的毛線泰迪熊，手工製作，是可愛的收藏品和禮物。",
      tags: ["毛線", "泰迪熊", "新人作品"],
      imgURLs: [
        "https://images.unsplash.com/photo-1515611309071-6cd7e12cace9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1236&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 8,
      created: "2023-10-04",
    },
    {
      id: 20,
      title: "手工卡片",
      description: "精心製作的手工卡片，搭配獨特設計，讓您的祝福更加特別。",
      tags: ["手工", "卡片", "新人作品", "父親節"],
      imgURLs: [
        "https://images.unsplash.com/photo-1605046177964-f13e1dc0a026?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 9,
      created: "2023-10-05",
    },
    {
      id: 21,
      title: "秋:夕陽紅楓掛畫",
      description: "以秋季夕陽和紅楓為靈感，手工繪製的掛畫，為您的家增色不少。",
      tags: ["秋", "掛畫", "新人作品"],
      imgURLs: [
        "https://images.unsplash.com/photo-1692987344047-a1632bd6d372?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1049&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 12,
      created: "2023-10-06",
    },
    {
      id: 22,
      title: "中國風元宵節燈籠",
      description: "精心製作的元宵節燈籠，營造節日氛圍，讓您共度溫馨佳節。",
      tags: ["中秋節", "中國風", "元宵節", "燈籠"],
      imgURLs: [
        "https://images.unsplash.com/photo-1603440706741-dcb3d225e093?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 7,
      created: "2023-10-08",
    },
    {
      id: 23,
      title: "元宵節燈籠",
      description: "色彩繽紛的元宵節燈籠，寓意喜慶和幸福，是節日裝飾的完美選擇。",
      tags: ["中秋節", "元宵節", "燈籠"],
      imgURLs: [
        "https://images.unsplash.com/photo-1601658996129-431877c1d0e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 5,
      created: "2023-10-09",
    },
    {
      id: 24,
      title: "元宵節燈籠（藍色橘色）",
      description: "以藍色橘色為主題的元宵節燈籠，寓意平安和祥和，為節日增色不少。",
      tags: ["中秋節", "元宵節", "藍色", "橘色", "燈籠"],
      imgURLs: [
        "https://images.unsplash.com/photo-1601658967716-7ff05dc5ff91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 3,
      created: "2023-10-10",
    },
    {
      id: 25,
      title: "男仕皮夾",
      description: "精心製作的男士皮夾，以高品質皮革製成，簡約時尚，是理想的男士配件。",
      tags: ["父親節", "皮夾", "熱門"],
      imgURLs: [
        "https://images.unsplash.com/photo-1628483211662-9bcc692c46dc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1972&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 10,
      created: "2023-10-11",
    },
    {
      id: 26,
      title: "爸爸領帶",
      description: "特製的父親節領帶，寓意著尊敬和感激，是送給爸爸的特別禮物。",
      tags: ["父親節", "領帶"],
      imgURLs: [
        "https://images.unsplash.com/photo-1591729651537-476fda03849d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1925&q=80",
      ],
      shopLinks: [""],
      author: "",
      like: 8,
      created: "2023-10-12",
    },
  ],
};
