export default {
  enableCollapseSearch: false,
  route: "/",
  interests: [
    {
      id: 0,
      titleZH: "木工",
      titleEN: "Woodworking",
    },
    {
      id: 1,
      titleZH: "文具",
      titleEN: "Stationery",
    },
    {
      id: 2,
      titleZH: "紙藝",
      titleEN: "Paper Crafts",
    },
    {
      id: 3,
      titleZH: "繪畫和插畫",
      titleEN: "Painting and Illustration",
    },
    {
      id: 4,
      titleZH: "雕刻",
      titleEN: "Sculpture",
    },
    {
      id: 5,
      titleZH: "皮革製品",
      titleEN: "Leather Goods",
    },
    {
      id: 6,
      titleZH: "環保再生製品",
      titleEN: "Eco-friendly Upcycled Products",
    },
    {
      id: 7,
      titleZH: "軟玩具和娃娃",
      titleEN: "Soft Toys and Dolls",
    },
    {
      id: 8,
      titleZH: "拼貼和雕貼",
      titleEN: "Collage and Decoupage",
    },
    {
      id: 9,
      titleZH: "影視手工藝",
      titleEN: "Film and TV Crafts",
    },
    {
      id: 10,
      titleZH: "DIY工具和工藝材料",
      titleEN: "DIY Tools and Craft Materials",
    },
  ],
  hotNow: [
    {
      id: 0,
      titleZH: "設計家具",
      titleEN: "Design Furniture",
    },
    {
      id: 1,
      titleZH: "婚禮小物",
      titleEN: "Wedding Accessories",
    },
    {
      id: 2,
      titleZH: "旅行用品",
      titleEN: "Travel Goods",
    },
    {
      id: 3,
      titleZH: "手工花藝",
      titleEN: "Handmade Floral",
    },
    {
      id: 4,
      titleZH: "環保愛地球",
      titleEN: "Environmental Friendly",
    },
    {
      id: 5,
      titleZH: "香氛蠟燭",
      titleEN: "Scented Candle",
    },
  ],
  materials: [
    "木材",
    "金屬",
    "玻璃",
    "陶瓷",
    "布料、紡織品",
    "皮革",
    "紙張、紙板",
    "塑料",
    "石材",
    "珠寶材料",
    "粘土",
    "植物材料",
    "電子元件",
    "食品材料",
    "水彩、油畫顏料",
    "蠟燭材料",
    "香薰材料",
    "環保再生材料",
    "石膏、混凝土",
    "軟性材質",
    "酸性材質",
    "金箔、銀箔",
    "複合材料",
    "其他",
  ],
  category: [
    "木工",
    "飾品",
    "文具",
    "織品",
    "陶瓷和陶器",
    "粘土創作",
    "珠寶",
    "紙藝",
    "玻璃工藝",
    "古董和復古裝飾",
    "繪畫和插畫",
    "雕刻",
    "皮革製品",
    "美食工藝",
    "蠟燭和香薰",
    "音樂和樂器",
    "環保再生製品",
    "植物和園藝",
    "軟玩具和娃娃",
    "拼貼和雕貼",
    "電子手工藝",
    "空間設計和裝飾",
    "影視手工藝",
    "創意裝置藝術",
    "DIY工具和工藝材料",
  ],
  crafts: [
    {
      id: 0,
      title: "香芬蠟燭",
      description:
        "散發著迷人香氛的蠟燭，讓您瞬間放鬆並營造溫馨氛圍。完美選擇，無論是為了為家裡增添溫馨氛圍，或送給親朋好友，帶來特別的禮物體驗。",
      tags: ["聖誕節", "可愛"],
      imgURLs: [
        "https://images.unsplash.com/photo-1610283795609-edb9f19436a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1972&q=80",
        "https://images.unsplash.com/photo-1612293905607-b003de9e54fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
        "https://images.unsplash.com/photo-1570823635306-250abb06d4b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        "https://images.unsplash.com/photo-1613068431228-8cb6a1e92573?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
        "https://images.unsplash.com/photo-1604172083143-081d302edb4d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEyfHx8ZW58MHx8fHx8&auto=format&fit=crop&w=500&q=60",
      ],
      shopLinks: [""],
      author: "不會飛的兔子",
    },
    {
      id: 1,
      title: "針織窗簾",
      description: "精心製作的針織窗簾，為您的家居增添溫馨氛圍。",
      tags: ["窗簾", "針織"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 2,
      title: "乾燥花花盆",
      description: "特製的花盆，搭配精選乾燥花卉，為您的室內空間增色不少。",
      tags: ["花盆", "乾燥花"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 3,
      title: "愛心裝飾",
      description: "手工打造的愛心裝飾，帶來愛和溫暖的氛圍，適合用於家居裝飾或送禮。",
      tags: ["愛心", "裝飾"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 4,
      title: "乾燥花",
      description: "精心挑選的乾燥花束，保留了自然美，為您的生活增添了一抹自然的色彩。",
      tags: ["乾燥花", "花束"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 5,
      title: "毛線袋子",
      description: "經過精湛的毛線工藝製作而成，輕巧實用，是您日常生活的好幫手。",
      tags: ["毛線", "袋子"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 6,
      title: "陶杯",
      description: "手工製作的陶瓷杯，質感優良，為您的茶時光增色不少。",
      tags: ["陶杯", "陶瓷"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 7,
      title: "手工肥皂架",
      description: "精心製作的手工肥皂架，美觀實用，讓肥皂保持乾燥，延長使用壽命。",
      tags: ["肥皂架", "手工"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 8,
      title: "檸檬陶盤",
      description: "以檸檬為靈感，手工打造的陶瓷盤子，為您的餐桌增添一份清新。",
      tags: ["陶盤", "檸檬"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
    {
      id: 9,
      title: "手工肥皂",
      description: "純手工製作，天然成分，呵護您的肌膚，讓您感受自然的清新。",
      tags: ["手工肥皂", "天然"],
      imgURLs: [""],
      shopLinks: [""],
      author: "",
    },
  ],

  craftSelect: [1, 2, 3, 4, 5, 6, 7, 8, 9],
};
