export default {
  enableCollapseSearch: false,
  route: "/",
  interests: [
    {
      id: 1,
      titleZH: "木工",
      titleEN: "Woodworking",
    },
    {
      id: 2,
      titleZH: "文具",
      titleEN: "Stationery",
    },
    {
      id: 3,
      titleZH: "紙藝",
      titleEN: "Paper Crafts",
    },
    {
      id: 4,
      titleZH: "繪畫和插畫",
      titleEN: "Painting and Illustration",
    },
    {
      id: 5,
      titleZH: "雕刻",
      titleEN: "Sculpture",
    },
    {
      id: 6,
      titleZH: "皮革製品",
      titleEN: "Leather Goods",
    },
    {
      id: 7,
      titleZH: "環保再生製品",
      titleEN: "Eco-friendly Upcycled Products",
    },
    {
      id: 8,
      titleZH: "軟玩具和娃娃",
      titleEN: "Soft Toys and Dolls",
    },
    {
      id: 9,
      titleZH: "拼貼和雕貼",
      titleEN: "Collage and Decoupage",
    },
    {
      id: 10,
      titleZH: "影視手工藝",
      titleEN: "Film and TV Crafts",
    },
    {
      id: 11,
      titleZH: "DIY工具和工藝材料",
      titleEN: "DIY Tools and Craft Materials",
    },
  ],
  hotNow: [
    {
      id: 1,
      titleZH: "設計家具",
      titleEN: "Design Furniture",
    },
    {
      id: 2,
      titleZH: "婚禮小物",
      titleEN: "Wedding Accessories",
    },
    {
      id: 3,
      titleZH: "旅行用品",
      titleEN: "Travel Goods",
    },
    {
      id: 4,
      titleZH: "手工花藝",
      titleEN: "Handmade Floral",
    },
    {
      id: 5,
      titleZH: "環保愛地球",
      titleEN: "Environmental Friendly",
    },
    {
      id: 6,
      titleZH: "香氛蠟燭",
      titleEN: "Scented Candle",
    },
  ],
  materials: [
    "木材",
    "金屬",
    "玻璃",
    "陶瓷",
    "布料/紡織品",
    "皮革",
    "紙張/紙板",
    "塑料",
    "石材",
    "珠寶材料",
    "粘土",
    "植物材料",
    "電子元件",
    "食品材料",
    "水彩/油畫顏料",
    "蠟燭材料",
    "香薰材料",
    "環保再生材料",
    "石膏/混凝土",
    "軟性材質",
    "酸性材質",
    "金箔/銀箔",
    "複合材料",
    "其他",
  ],
  category: [
    "木工",
    "飾品",
    "文具",
    "織品",
    "陶瓷和陶器",
    "粘土創作",
    "珠寶",
    "紙藝",
    "玻璃工藝",
    "古董和復古裝飾",
    "繪畫和插畫",
    "雕刻",
    "皮革製品",
    "美食工藝",
    "蠟燭和香薰",
    "音樂和樂器",
    "環保再生製品",
    "植物和園藝",
    "軟玩具和娃娃",
    "拼貼和雕貼",
    "電子手工藝",
    "空間設計和裝飾",
    "影視手工藝",
    "創意裝置藝術",
    "DIY工具和工藝材料",
  ],
};
